source_dir = "addmo_examples/executables"

output_dir = "addmo_examples/executables"

include = [
    "exe_data_tuning_auto.py",
    "exe_data_tuning_fixed.py",
    "exe_model_tuning.py",
    "exe_data_insights.py"
]

