path_to_csv: "" # path to the csv file
name_of_raw_data: "training_data"  # Name of raw data
name_of_tuning: ""
period:
  start: "10.10.2023 00:00:00" # None or in DD.MM.YYYY HH:mm:ss format
  end: "10.10.2023 23:59:59"   # None or in DD.MM.YYYY HH:mm:ss format
target: "Strom Kaelteerzeugung NK"  # Output of prediction
features:  # Input for prediction
  ["Aussentemperatur",
  "Verdampfungstemperatur NK",
  "rel. Belegung",
  "Gaskuehlertemperatur",
  "Sollwert Verdampfungstemperatur NK",
  "Sauggastemperatur NK",
  "Sollwert Gaskuehlertemperatur",
  "Sollwert Verdampfungstemperatur TK",
  "Sauggastemperatur TK",
  "Aussentemperatur___diff",
  "Aussentemperatur___lag1"]