# from aixtra_use_case.sweeps import sweep_ed_usecase_boptest
# sweep_ed_usecase_boptest

from aixtra_use_case.sweeps import sweep_ed_usecase_boptest_tuning
sweep_ed_usecase_boptest_tuning

from aixtra_use_case.sweeps import sweep_ed_usecase_boptest_noTune_scikit
sweep_ed_usecase_boptest_noTune_scikit

from aixtra_use_case.sweeps import sweep_ed_usecase_boptest_tuning_scikit
sweep_ed_usecase_boptest_tuning_scikit

# from aixtra_use_case.sweeps import sweep_ed_usecase_carnot
# sweep_ed_usecase_carnot
#
# from aixtra_use_case.sweeps import sweep_ed_usecase_carnot_tuning
# sweep_ed_usecase_carnot_tuning
#
# from aixtra_use_case.sweeps import sweep_ed_usecase_carnot_tuning_scikit
# sweep_ed_usecase_carnot_tuning_scikit
#
# from aixtra_use_case.sweeps import sweep_ed_usecase_carnot_noTune_scikit
# sweep_ed_usecase_carnot_noTune_scikit


