name: Python CI

on:
  push:
    branches:
      - mre-rpa
  pull_request:
    branches:
      - mre-rpa

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  ci:
    uses: RWTH-EBC/ci_templates/.github/workflows/ci_pipeline.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    with:
      PYTHON_VERSION: "3.10"
      PYTHON_TEST_MATRIX: '["3.10"]'
      USE_PYLINT: true
      USE_RUFF: true
      BUILD_PACKAGE: true
      GENERATE_DOCUMENTATION: true
      GH_PAGES: true
      EXECUTE_COVERAGE_TEST: true

